In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [ ]:
X_train = pd.read_csv('/kaggle/input/trainhar/X_train.txt', delim_whitespace=True)
X_train=X_train.to_numpy()

In [ ]:
X_train.shape

In [21]:
y_train=pd.read_csv('/kaggle/input/trainhar/y_train.txt', delim_whitespace=True,squeeze=True)
y_train=y_train.to_numpy()

In [ ]:
y_train.shape

In [ ]:
X_test=pd.read_csv('/kaggle/input/harkrsdmk/X_test.txt', delim_whitespace=True)
X_test=X_test.to_numpy()

In [22]:
X_test.shape

(2946, 561)

In [ ]:
len(X_test[2])

In [ ]:
y_test=pd.read_csv('/kaggle/input/harkrsdmk/y_test.txt', delim_whitespace=True,squeeze=True)
y_test=y_test.to_numpy()

In [ ]:
y_test.shape

In [ ]:
from datetime import datetime
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

def train(model,X_train,y_train,X_test,y_test):
    train_start_time=datetime.now()
    print("training the model has begin...")
    model.fit(X_train,y_train)
    print("Done..")
    train_end_time=datetime.now()
    print(f'Training time is {train_end_time-train_start_time}')
    
    print("Predicting Test data ...")
    y_pred=model.predict(X_test)
    print("Done ..")
    
    accuracy = metrics.accuracy_score(y_true=y_test, y_pred=y_pred)
    print("--------------")
    print("Accuracy")
    print("---------------")
    print(accuracy)
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("--------------")
    print("Confusion matrix")
    print("---------------")
    print(cm)
    
    return model
    

In [ ]:
from sklearn import linear_model

In [ ]:
parameters = {'C':[0.01, 0.1, 1, 10, 20, 30], 'penalty':['l2','l1']}
log_reg = linear_model.LogisticRegression()
log_reg_grid = GridSearchCV(log_reg, param_grid=parameters, cv=10, verbose=1, n_jobs=-1)
model=  train(log_reg_grid, X_train, y_train, X_test, y_test)

In [23]:

print('--------------------------')
print('|      Best Estimator     |')
print('--------------------------')
print('\n\t{}\n'.format(model.best_estimator_))


    # parameters that gave best results while performing grid search
print('--------------------------')
print('|     Best parameters     |')
print('--------------------------')
print('\tParameters of best estimator : \n\n\t{}\n'.format(model.best_params_))


    #  number of cross validation splits
print('---------------------------------')
print('|   No of CrossValidation sets   |')
print('--------------------------------')
print('\n\tTotal numbre of cross validation sets: {}\n'.format(model.n_splits_))


    # Average cross validated score of the best estimator, from the Grid Search 
print('--------------------------')
print('|        Best Score       |')
print('--------------------------')
print('\n\tAverage Cross Validate scores of best estimator : \n\n\t{}\n'.format(model.best_score_))

--------------------------
|      Best Estimator     |
--------------------------

	SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

--------------------------
|     Best parameters     |
--------------------------
	Parameters of best estimator : 

	{'C': 1, 'kernel': 'linear'}

---------------------------------
|   No of CrossValidation sets   |
--------------------------------

	Total numbre of cross validation sets: 4

--------------------------
|        Best Score       |
--------------------------

	Average Cross Validate scores of best estimator : 

	0.9400129901439578



In [ ]:
k=np.random.randint(1,2000)
print(model.predict(X_test[k].reshape(1,-1)))
print(y_test[k])

In [ ]:
from sklearn.svm import SVC
parameters={'C':[1,10],'kernel':['linear','rbf']}
s_reg = SVC()
s_reg_grid = GridSearchCV(s_reg, param_grid=parameters, cv=4, verbose=1, n_jobs=-1)
model=  train(s_reg_grid, X_train, y_train, X_test, y_test)

In [24]:

print('--------------------------')
print('|      Best Estimator     |')
print('--------------------------')
print('\n\t{}\n'.format(model.best_estimator_))


    # parameters that gave best results while performing grid search
print('--------------------------')
print('|     Best parameters     |')
print('--------------------------')
print('\tParameters of best estimator : \n\n\t{}\n'.format(model.best_params_))


    #  number of cross validation splits
print('---------------------------------')
print('|   No of CrossValidation sets   |')
print('--------------------------------')
print('\n\tTotal numbre of cross validation sets: {}\n'.format(model.n_splits_))


    # Average cross validated score of the best estimator, from the Grid Search 
print('--------------------------')
print('|        Best Score       |')
print('--------------------------')
print('\n\tAverage Cross Validate scores of best estimator : \n\n\t{}\n'.format(model.best_score_))

--------------------------
|      Best Estimator     |
--------------------------

	SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

--------------------------
|     Best parameters     |
--------------------------
	Parameters of best estimator : 

	{'C': 1, 'kernel': 'linear'}

---------------------------------
|   No of CrossValidation sets   |
--------------------------------

	Total numbre of cross validation sets: 4

--------------------------
|        Best Score       |
--------------------------

	Average Cross Validate scores of best estimator : 

	0.9400129901439578



In [ ]:
from sklearn.tree import DecisionTreeClassifier
parameters={'max_depth':np.arange(3,12,2)}
d_reg = DecisionTreeClassifier(criterion='entropy')
d_reg_grid = GridSearchCV(d_reg, param_grid=parameters, cv=5, verbose=1, n_jobs=-1)
decision=  train(d_reg_grid, X_train, y_train, X_test, y_test)

In [25]:

print('--------------------------')
print('|      Best Estimator     |')
print('--------------------------')
print('\n\t{}\n'.format(decision.best_estimator_))


    # parameters that gave best results while performing grid search
print('--------------------------')
print('|     Best parameters     |')
print('--------------------------')
print('\tParameters of best estimator : \n\n\t{}\n'.format(decision.best_params_))


    #  number of cross validation splits
print('---------------------------------')
print('|   No of CrossValidation sets   |')
print('--------------------------------')
print('\n\tTotal numbre of cross validation sets: {}\n'.format(decision.n_splits_))


    # Average cross validated score of the best estimator, from the Grid Search 
print('--------------------------')
print('|        Best Score       |')
print('--------------------------')
print('\n\tAverage Cross Validate scores of best estimator : \n\n\t{}\n'.format(decision.best_score_))

--------------------------
|      Best Estimator     |
--------------------------

	DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

--------------------------
|     Best parameters     |
--------------------------
	Parameters of best estimator : 

	{'max_depth': 5}

---------------------------------
|   No of CrossValidation sets   |
--------------------------------

	Total numbre of cross validation sets: 5

--------------------------
|        Best Score       |
--------------------------

	Average Cross Validate scores of best estimator : 

	0.8711755157535481



In [ ]:
from sklearn.ensemble import RandomForestClassifier
params = {'n_estimators': np.arange(10,121,20), 'max_depth':np.arange(3,15,2)}
rfc = RandomForestClassifier()
rfc_grid = GridSearchCV(rfc, param_grid=params, n_jobs=-1)
rfc_grid_results = train(rfc_grid, X_train, y_train, X_test, y_test)

In [26]:

print('--------------------------')
print('|      Best Estimator     |')
print('--------------------------')
print('\n\t{}\n'.format(rfc_grid_results.best_estimator_))


    # parameters that gave best results while performing grid search
print('--------------------------')
print('|     Best parameters     |')
print('--------------------------')
print('\tParameters of best estimator : \n\n\t{}\n'.format(rfc_grid_results.best_params_))


    #  number of cross validation splits
print('---------------------------------')
print('|   No of CrossValidation sets   |')
print('--------------------------------')
print('\n\tTotal numbre of cross validation sets: {}\n'.format(rfc_grid_results.n_splits_))


    # Average cross validated score of the best estimator, from the Grid Search 
print('--------------------------')
print('|        Best Score       |')
print('--------------------------')
print('\n\tAverage Cross Validate scores of best estimator : \n\n\t{}\n'.format(rfc_grid_results.best_score_))

--------------------------
|      Best Estimator     |
--------------------------

	RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=11, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=110,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

--------------------------
|     Best parameters     |
--------------------------
	Parameters of best estimator : 

	{'max_depth': 11, 'n_estimators': 110}

---------------------------------
|   No of CrossValidation sets   |
--------------------------------

	Total numbre of cross validation sets: 5

--------------------------
|        Best Score       |
------------

In [ ]:
!pip install xgboost

In [ ]:
from xgboost import XGBClassifier
xclassifier=XGBClassifier()
parameters={'max_depth':[20,50],'learning_rate':[.005,.01],'n_estimators':[50,100]}
xgb_grid = GridSearchCV(xclassifier, param_grid=params, n_jobs=-1)
xgb_grid_results = train(xgb_grid, X_train, y_train, X_test, y_test)

In [27]:

print('--------------------------')
print('|      Best Estimator     |')
print('--------------------------')
print('\n\t{}\n'.format(xgb_grid_results.best_estimator_))


    # parameters that gave best results while performing grid search
print('--------------------------')
print('|     Best parameters     |')
print('--------------------------')
print('\tParameters of best estimator : \n\n\t{}\n'.format(xgb_grid_results.best_params_))


    #  number of cross validation splits
print('---------------------------------')
print('|   No of CrossValidation sets   |')
print('--------------------------------')
print('\n\tTotal numbre of cross validation sets: {}\n'.format(xgb_grid_results.n_splits_))


    # Average cross validated score of the best estimator, from the Grid Search 
print('--------------------------')
print('|        Best Score       |')
print('--------------------------')
print('\n\tAverage Cross Validate scores of best estimator : \n\n\t{}\n'.format(xgb_grid_results.best_score_))

--------------------------
|      Best Estimator     |
--------------------------


NameError: name 'xgb_grid_results' is not defined

In [28]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu', input_dim =X_train.shape[1]))
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softmax'))
    classifier.compile(optimizer = optimizer, loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [32],
              'epochs': [25],
              'optimizer': ['adam']}
ann_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',cv=2)
print("Training has begin")
start_time=datetime.now()
ann_model = ann_search.fit(X_train, y_train)
end_time=datetime.now()
print("Done...")
print("Time for training ".format(end_time-start_time))


Using TensorFlow backend.


Training has begin
Epoch 1/25
3675/3675 [==============================] - 1s 376us/step - loss: 0.4941 - accuracy: 0.7804
Epoch 2/25
3675/3675 [==============================] - 0s 107us/step - loss: 0.1701 - accuracy: 0.9306
Epoch 3/25
3675/3675 [==============================] - 0s 108us/step - loss: 0.1150 - accuracy: 0.9548
Epoch 4/25
3675/3675 [==============================] - 1s 189us/step - loss: 0.1167 - accuracy: 0.9524
Epoch 5/25
3675/3675 [==============================] - 0s 130us/step - loss: 0.1327 - accuracy: 0.9543
Epoch 6/25
3675/3675 [==============================] - 0s 107us/step - loss: 0.0628 - accuracy: 0.9731
Epoch 7/25
3675/3675 [==============================] - 0s 121us/step - loss: 0.0649 - accuracy: 0.9769
Epoch 8/25
3675/3675 [==============================] - 0s 105us/step - loss: 0.0550 - accuracy: 0.9818
Epoch 9/25
3675/3675 [==============================] - 0s 108us/step - loss: 0.0493 - accuracy: 0.9810
Epoch 10/25
3675/3675 [======================

In [29]:
print("Predicting Test data ...")
y_pred=ann_model.predict(X_test)
print("Done ..")
    
accuracy = metrics.accuracy_score(y_true=y_test, y_pred=y_pred)
print("--------------")
print("Accuracy")
print("---------------")
print(accuracy)
cm = metrics.confusion_matrix(y_test, y_pred)
print("--------------")
print("Confusion matrix")
print("---------------")
print(cm)

Predicting Test data ...
Done ..
--------------
Accuracy
---------------
0.9426340801086218
--------------
Confusion matrix
---------------
[[482   0  14   0   0   0]
 [ 36 428   7   0   0   0]
 [  4  15 401   0   0   0]
 [  0   2   0 411  78   0]
 [  0   0   0  12 519   0]
 [  0   0   0   0   1 536]]


--------------------------
|      Best Estimator     |
--------------------------


--------------------------
|     Best parameters     |
--------------------------
	Parameters of best estimator : 

	{'batch_size': 32, 'epochs': 25, 'optimizer': 'adam'}

---------------------------------
|   No of CrossValidation sets   |
--------------------------------

	Total numbre of cross validation sets: 2

--------------------------
|        Best Score       |
--------------------------

	Average Cross Validate scores of best estimator : 

	0.9189245186649198

